"""
Report generation and saving for Scout.

Produces:
  - Markdown report (.md) — human-readable, well-formatted
  - JSON sidecar (.json) — machine-readable metadata + full data

File naming: YYYYMMDD_HHMMSS_<slug>.md / .json
"""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path

from models import ScoutReport, PageContent, FetchStatus
from exceptions import ReporterError

logger = logging.getLogger("scout.reporter")

# ─── HELPERS ─────────────────────────────────────────────────────────────────

def _sanitize_slug(text: str, max_len: int = 55) -> str:
    """Convert goal text to a safe filename slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "_", text)
    text = text.strip("_-")
    return text[:max_len]


def _status_badge(status: FetchStatus) -> str:
    badges = {
        FetchStatus.SUCCESS: "✓",
        FetchStatus.SNIPPET_ONLY: "~",
        FetchStatus.BLOCKED: "✗",
        FetchStatus.TIMEOUT: "⏱",
        FetchStatus.ERROR: "✗",
    }
    return badges.get(status, "?")


# ─── MARKDOWN BUILDER ────────────────────────────────────────────────────────

_CONFIDENCE_BADGE = {
    "high":   "High",
    "medium": "Medium",
    "low":    "Low",
}

_METHOD_LABEL = {
    "dspy":       "DSPy ChainOfThought",
    "instructor": "Instructor (structured)",
    "raw":        "Raw LLM",
}


def _build_markdown(report: ScoutReport) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M:%S")
    duration = f"{report.run_duration_seconds:.1f}s"
    confidence = _CONFIDENCE_BADGE.get(report.confidence, report.confidence)
    method = _METHOD_LABEL.get(report.extraction_method, report.extraction_method)

    # Header
    lines = [
        "# Scout Report",
        "",
        f"> **Goal:** {report.goal}",
        f"> **Generated:** {ts}  ",
        f"> **Model:** `{report.model_used}`  ",
        f"> **Extraction:** {method}  ",
        f"> **Confidence:** {confidence}  ",
        f"> **Duration:** {duration}  ",
        f"> **Sources:** {report.pages_successful} fetched successfully, "
        f"{report.pages_failed} failed/snippet-only",
        "",
        "---",
        "",
    ]

    # Insights (LLM output — already markdown from DSPy or raw)
    lines += [
        "## Insights",
        "",
        report.insights.strip(),
        "",
        "---",
        "",
    ]

    # Source table
    lines += [
        "## Sources Scraped",
        "",
        "| # | Status | Title | URL |",
        "|---|--------|-------|-----|",
    ]
    for i, page in enumerate(report.pages, 1):
        badge = _status_badge(page.fetch_status)
        title = page.title.replace("|", "\\|")[:60]
        url = page.url
        lines.append(f"| {i} | {badge} | {title} | {url} |")

    lines += ["", "---", ""]

    # Fetch legend
    lines += [
        "<details>",
        "<summary>Fetch status legend</summary>",
        "",
        "- ✓ Full page text extracted",
        "- ~ Snippet only (page blocked or extraction failed)",
        "- ✗ Blocked or error",
        "- ⏱ Timed out",
        "",
        "</details>",
        "",
        f"*Generated by [Scout](https://github.com/) — powered by `{report.model_used}`*",
    ]

    return "\n".join(lines)


# ─── JSON BUILDER ─────────────────────────────────────────────────────────────

def _build_json(report: ScoutReport) -> str:
    data = {
        "goal": report.goal,
        "generated_at": report.generated_at.isoformat(),
        "model_used": report.model_used,
        "run_duration_seconds": round(report.run_duration_seconds, 2),
        "stats": {
            "total_sources": len(report.pages),
            "successful": report.pages_successful,
            "failed": report.pages_failed,
        },
        "insights": report.insights,
        "sources": [
            {
                "rank": i,
                "title": p.title,
                "url": p.url,
                "fetch_status": p.fetch_status.value,
                "char_count": p.char_count,
                "fetch_error": p.fetch_error,
            }
            for i, p in enumerate(report.pages, 1)
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False)


# ─── SAVE ─────────────────────────────────────────────────────────────────────

class SavedReport:
    """Paths where report was saved."""
    __slots__ = ("md_path", "json_path")

    def __init__(self, md_path: Path, json_path: Path):
        self.md_path = md_path
        self.json_path = json_path

    def __str__(self):
        return str(self.md_path)


def save_report(report: ScoutReport, output_dir: str | Path) -> SavedReport:
    """
    Save report as .md and .json to output_dir.
    Returns SavedReport with paths to both files.
    Raises ReporterError on write failure.
    """
    out = Path(output_dir).expanduser()
    if not out.is_absolute():
        out = Path.cwd() / out
    out.mkdir(parents=True, exist_ok=True)

    ts = report.generated_at.strftime("%Y%m%d_%H%M%S")
    slug = _sanitize_slug(report.goal)
    base_name = f"{ts}_{slug}"

    md_path = out / f"{base_name}.md"
    json_path = out / f"{base_name}.json"

    try:
        md_content = _build_markdown(report)
        md_path.write_text(md_content, encoding="utf-8")
        logger.info("Saved markdown: %s", md_path)

        json_content = _build_json(report)
        json_path.write_text(json_content, encoding="utf-8")
        logger.info("Saved JSON: %s", json_path)

    except OSError as e:
        raise ReporterError(f"Failed to write report to {out}: {e}") from e

    return SavedReport(md_path=md_path, json_path=json_path)


def print_report_preview(report: ScoutReport, max_lines: int = 40) -> None:
    """Print a preview of the insights to stdout."""
    lines = report.insights.strip().splitlines()
    preview = "\n".join(lines[:max_lines])
    if len(lines) > max_lines:
        preview += f"\n\n... ({len(lines) - max_lines} more lines in file)"
    print(preview)
